version: "3"

services:
  web:
    container_name: django_web
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres_web
    volumes:
      - postgres_data:/var/common/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:



